import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/shared/layout/Header/Header";
import Footer from "@/shared/layout/Footer/Footer";
import StoreProvider from "@/store/provider";
import ToastProvider from "@/shared/providers/ToastProvider";

export const metadata: Metadata = {
  title: "DigiBox | فروشگاه اینترنتی دیجی باکس",
  description: "Generated by DigiBox",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html dir="rtl" lang="fa-IR">
      <body>
        <StoreProvider>
          <Header />
          <main>
            {children}
            <ToastProvider />
          </main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
